// <auto-generated />
using System;
using BlogAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BlogAPI.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20240726213455_InitialDatabaseMigration")]
    partial class InitialDatabaseMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BlogAPI.Model.DTO.category", b =>
                {
                    b.Property<Guid>("category_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("category_name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("category_id");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("BlogAPI.Model.DTO.chapter", b =>
                {
                    b.Property<Guid>("chapter_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("chapter_content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("post_id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("volume_id")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("chapter_id");

                    b.HasIndex("volume_id");

                    b.ToTable("Chapters");
                });

            modelBuilder.Entity("BlogAPI.Model.DTO.credential", b =>
                {
                    b.Property<Guid>("user_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("cred_createDate")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("cred_passWord")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("cred_role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("cred_userName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("user_id");

                    b.ToTable("Credentials");
                });

            modelBuilder.Entity("BlogAPI.Model.DTO.post", b =>
                {
                    b.Property<Guid>("post_id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("post_createDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("post_hidden")
                        .HasColumnType("bit");

                    b.Property<string>("post_longDes")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("post_shortDes")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("post_status")
                        .HasColumnType("bit");

                    b.Property<string>("post_title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("post_type")
                        .HasColumnType("bit");

                    b.HasKey("post_id");

                    b.ToTable("Posts");
                });

            modelBuilder.Entity("BlogAPI.Model.DTO.post_category_temp", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("category_id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("post_id")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("id");

                    b.HasIndex("category_id");

                    b.HasIndex("post_id");

                    b.ToTable("PostCategories");
                });

            modelBuilder.Entity("BlogAPI.Model.DTO.user", b =>
                {
                    b.Property<Guid>("user_id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("user_birthDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("user_firstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("user_lastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("user_id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("BlogAPI.Model.DTO.volume", b =>
                {
                    b.Property<Guid>("volume_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("post_id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("volume_name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("volume_id");

                    b.HasIndex("post_id");

                    b.ToTable("Volumes");
                });

            modelBuilder.Entity("BlogAPI.Model.DTO.chapter", b =>
                {
                    b.HasOne("BlogAPI.Model.DTO.volume", "volume")
                        .WithMany("chapter")
                        .HasForeignKey("volume_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("volume");
                });

            modelBuilder.Entity("BlogAPI.Model.DTO.post", b =>
                {
                    b.HasOne("BlogAPI.Model.DTO.user", "user")
                        .WithMany("post")
                        .HasForeignKey("post_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("user");
                });

            modelBuilder.Entity("BlogAPI.Model.DTO.post_category_temp", b =>
                {
                    b.HasOne("BlogAPI.Model.DTO.category", "category")
                        .WithMany("post_category_temp")
                        .HasForeignKey("category_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BlogAPI.Model.DTO.post", "post")
                        .WithMany("post_category_temp")
                        .HasForeignKey("post_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("category");

                    b.Navigation("post");
                });

            modelBuilder.Entity("BlogAPI.Model.DTO.user", b =>
                {
                    b.HasOne("BlogAPI.Model.DTO.credential", "credential")
                        .WithOne("user")
                        .HasForeignKey("BlogAPI.Model.DTO.user", "user_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("credential");
                });

            modelBuilder.Entity("BlogAPI.Model.DTO.volume", b =>
                {
                    b.HasOne("BlogAPI.Model.DTO.post", "post")
                        .WithMany("volume")
                        .HasForeignKey("post_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("post");
                });

            modelBuilder.Entity("BlogAPI.Model.DTO.category", b =>
                {
                    b.Navigation("post_category_temp");
                });

            modelBuilder.Entity("BlogAPI.Model.DTO.credential", b =>
                {
                    b.Navigation("user")
                        .IsRequired();
                });

            modelBuilder.Entity("BlogAPI.Model.DTO.post", b =>
                {
                    b.Navigation("post_category_temp");

                    b.Navigation("volume");
                });

            modelBuilder.Entity("BlogAPI.Model.DTO.user", b =>
                {
                    b.Navigation("post");
                });

            modelBuilder.Entity("BlogAPI.Model.DTO.volume", b =>
                {
                    b.Navigation("chapter");
                });
#pragma warning restore 612, 618
        }
    }
}
